- id: '1706471276837'
  alias: Ouman logon cronjob
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /5
  condition: []
  action:
  - service: shell_command.ouman_logon
    data: {}
  mode: single
