## Ouman EH-800
## Insert these lines to configuration.yaml
## command_line row points to yaml file containing all sensors and switches for Ouman EH-800
## shell_command handles Ouman web interface session login in Home Assistant start (automation keeps it alive)
## input_text sets variable for Ouman EH-800 baseurl
## Remember to edit your user credentials and ip address after copying rows to your configuration


command_line: !include command_line.yaml

shell_command:
  ouman_logon: !secret ouman_logon

input_text:
  ouman_eh800_ip:
    name: Ouman IP-address
    initial: http://192.168.1.1:80/
