## Insert these lines to configuration.yaml
## command_line row points to yaml file containing all sensors and switches for Ouman EH-800
## shell_command handles Ouman web interface session login in Home Assistant start (automation keeps it alive)
## Remember to edit your user credentials after copying row to your configuration

command_line: !include command_line.yaml

shell_command:
  ouman_logon: !secret ouman_logon
